definitions:
  handler.requestUser:
    properties:
      class:
        example: IE3A
        type: string
      icon:
        example: ""
        type: string
      name:
        example: ぴよ太郎
        type: string
      readme:
        example: ""
        type: string
      uid:
        example: 220000
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/clubs:
    get:
      responses: {}
      summary: クラブ一覧を取得
  /v1/clubs/{id}:
    get:
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: クラブを取得
  /v1/clubs/{id}/activities:
    get:
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: クラブの活動を取得
  /v1/me:
    get:
      responses: {}
      summary: 自分のユーザー情報を取得する
  /v1/users:
    post:
      parameters:
      - description: ユーザー情報
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.requestUser'
      responses: {}
      summary: ユーザーを作成する
swagger: "2.0"
