openapi: "3.0.0"
info:
  title: "API"
  version: "1.0.0"

servers:
  - url: "http://localhost:3003"
    description: "Mock server"
  - url: "http://localhost:1337"
    description: "Local server"

paths:
  /me:
    get:
      $ref: "./paths/get-me.yml"
  /me/clubs:
    get:
      $ref: "./paths/get-me-clubs.yml"
  /clubs:
    get:
      $ref: "./paths/get-clubs.yml"
  /clubs/{club_id}:
    get:
      $ref: "./paths/get-club.yml"
  /clubs/{club_id}/members:
    get:
      $ref: "./paths/get-club-members.yml"
components:
  $ref: "./components.yml"
