openapi: "3.0.0"
info:
  title: "User API"
  version: "1.0.0"
paths:
  /users/{user_id}:
    get:
      $ref: "./paths/get-user.yml"
    # post:
    #   $ref: "./paths/user/post-user.yml"
components:
  $ref: "./components.yml"
