version: "3.9"

services:
  web:
    image: node:18.15.0-alpine
    container_name: clubActivity-web
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
    command: >
      sh -c "
        yarn &&
        yarn start --host 0.0.0.0
      "

  api:
    image: golang:1.19-alpine
    container_name: clubActivity-api
    working_dir: /go/src/app
    volumes:
      - ./api:/go/src/app
    ports:
      - '8080:8080'
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
    command: >
      sh -c "
        apk add --no-cache gcc musl-dev &&
        go install github.com/cosmtrek/air@latest &&
        air
      "

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "3001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "3002:8080"
    volumes:
      - ./mock:/mock
    environment:
      SWAGGER_JSON: /mock/openapi.yml

  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "3003:4010"
    command: mock -h 0.0.0.0 /mock/openapi.yml
    volumes:
      - ./mock:/mock

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: "sqlitebrowser"
    ports:
      - "3004:3000"
    volumes:
      - ./api/data.db:/config/data.db
      - ./config:/config
    environment: 
      - TZ=Asia/Tokyo
      - PUID=1000
      - PGID=1000

  # adminer:
  #   image: adminer
  #   container_name: "adminer"
  #   ports:
  #     - "3004:8080"