version: "3.9"

services:
  web:
    image: node:18.15.0-alpine
    container_name: clubActivity-web
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
    command: >
      sh -c "
        yarn &&
        yarn start --host 0.0.0.0
      "

  api:
    image: golang:1.19-alpine
    container_name: clubActivity-api
    working_dir: /go/src/app
    volumes:
      - ./api:/go/src/app
    ports:
      - '8080:8080'
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
    command: >
      sh -c "
        apk add --no-cache gcc musl-dev &&
        go install github.com/cosmtrek/air@latest &&
        air
      "