version: "3.9"

services:
  web:
    image: node:18.15.0-alpine
    container_name: clubActivity-web
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
    command: >
      sh -c "
        yarn &&
        yarn start --host 0.0.0.0
      "

  api:
    image: node:18.15.0-alpine
    container_name: clubActivity-api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - 1337:1337
    command: >
      sh -c "
        yarn &&
        yarn develop
      "
 
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "3001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "3002:8080"
    volumes:
      - ./mock:/mock
    environment:
      SWAGGER_JSON: /mock/openapi.yml

  swagger-api:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "3003:4010"
    command: mock -h 0.0.0.0 /mock/openapi.yaml
    volumes:
      - ./mock:/mock
